project_id = "nrqueogifxxdwladewey"

[functions.auth-status]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.app-version]
verify_jwt = false

[functions.health-check]
verify_jwt = false
