project_id = "nrqueogifxxdwladewey"

[functions.auth-status]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.app-version]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.bulk-sync]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.device-check]
verify_jwt = false

[functions.expire-licenses]
verify_jwt = false

[functions.classify-customers]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false
